# Generated by Django 5.1.6 on 2025-02-09 23:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=300)),
                ('director', models.CharField(blank=True, max_length=32)),
                ('year_of_release', models.DateTimeField(blank=True, null=True)),
                ('genre', models.CharField(choices=[('AC', 'Action'), ('BI', 'Biography'), ('CO', 'Comedy'), ('CR', 'Crime'), ('FA', 'Fantasy'), ('MY', 'Mystery'), ('FI', 'Fiction'), ('SA', 'Satire'), ('SF', 'Sci Fi'), ('DR', 'Drama'), ('HR', 'Horror'), ('RO', 'Romance'), ('TH', 'Thriller'), ('WR', 'War'), ('HS', 'History'), ('AD', 'Adventure'), ('AN', 'Animation'), ('DC', 'Documentary'), ('WE', 'Western'), ('PN', 'Pornography')], max_length=2)),
                ('is_classified_adults_only', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieRaterApi.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
