# Generated by Django 5.1.6 on 2025-02-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieRaterApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='is_classified_adults_only',
            new_name='is_generalView',
        ),
    ]
