# Generated by Django 5.1.6 on 2025-02-10 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieRaterApi', '0002_rename_is_classified_adults_only_movie_is_generalview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='is_generalView',
            new_name='is_classified_adult_view',
        ),
    ]
